{
  "pipe_parallel_size": 0,
  "model_parallel_size": 0,
  # "make_vocab_size_divisible_by": 1, # thuis param cause cuda index error

  # model settings
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,

  "attention_config": [[["flash"], 32]],


  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "adam",
     "params": {
       "lr": 0.00001,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },

   # batch / data settings
   "train_batch_size": 256,
   "train_micro_batch_size_per_gpu": 8,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

   # precision settings
   "precision": "bfloat16",
   "fp32_allreduce": true,
   "bf16": {
     "enabled": true
   },
   "data_types": {
     "grad_accum_dtype": "fp32"
   },

   # misc. training settings
   "train_iters": -1,
   "lr_decay_iters": 65000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup_iters": 2000,
   "checkpoint_factor": 5000,
   "eval_interval": 1000,

   # logging
   "log_interval": 1,
   "steps_per_print": 10,
   "wall_clock_breakdown": true,

  "train-data-paths": ["data/slimpajama/chunk1_text_document"],
  "valid-data-paths": ["./data/slimpajama/slimpajama_llama/test_text_document"],
  "test-data-paths": ["./data/benchmark_text/dev_text_document"],

  "vocab-file": "/mnt/petrelfs/share_data/llm_llama2/llm_llama2/llama-2-7b-hf/tokenizer.model",
  "tokenizer_type": "SPMTokenizer",
  "launcher": "slurm",
  "deepspeed_slurm": false,
  
  "do_train": 0,
  "do_valid": 1,
  "do_test": 0, 

  "load": "pm:s3://P_model_weights/zengzhiyuan/checkpoints/moefication/llama_7b_e32_postlocal/",
  "load_iteration": 60000,
  "no_load_optim": true, # not load optimizer
  "eval_results_prefix": "eval_results/llama1_e32_postlocal",

  "from_dense_to_moe": {
    "do_convert": false,
    "post": "local"
  },
  "moe_num_experts": 32,
  "ep_world_size": 8,
  "moe_top_k": 1,
  "moe_min_capacity": 0,
  "moe_freq": 2,
  "moe_aux_loss_weight": {
    "load_balance": 0.01,
    "zloss": 0,
    "entropy": 0,
    "kl_div": 0
  },
  "use_wandb": false
}